vtol_navigation_node:
  ros__parameters:
    cruise_altitude: 100.0
    fw_accept_radius: 80.0
    waypoints:
      x:
      - 0.0
      - 32.4
      - 64.3
      - 110.9
      - 172.4
      - 594.3
      - 648.2
      - 695.2
      - 800.0
      y:
      - 0.0
      - 291.4
      - 360.0
      - 416.4
      - 460.5
      - 590.4
      - 620.8
      - 661.1
      - 800.0
    tercom_analysis:
      mean_disc: 0.0
      recommended_altitude_m: 100.0
      total_distance_m: 1256.9
      max_terrain_m: 32.0
      max_gradient: 0.0479
      cable_utilization_pct: 20.9
      recovery:
      - wp_index: 0
        distance_m: 3403.2
        zone: red
      - wp_index: 1
        distance_m: 3306.9
        zone: red
      - wp_index: 2
        distance_m: 3328.1
        zone: red
      - wp_index: 3
        distance_m: 3350.4
        zone: red
      - wp_index: 4
        distance_m: 3373.8
        zone: red
      - wp_index: 5
        distance_m: 3714.9
        zone: red
      - wp_index: 6
        distance_m: 3744.3
        zone: red
      - wp_index: 7
        distance_m: 3774.6
        zone: red
      - wp_index: 8
        distance_m: 3870.8
        zone: red
